version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_beverage
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - beverage_data:/var/lib/mysql

volumes:
  beverage_data:

#version: "3.9"
#
#networks:
#  beverage-network:
#    driver: bridge
#
#services:
#  beverage-mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#    ports:
#      - "3306:3306"
#    networks:
#      - beverage-network
#
#  beverage-redis:
#    image: redis:6.2.1-alpine
#        networks:
#          - beverage-network
#
#  beverage-api:
#    image: beverage-api
#    command: ["/wait-for-it.sh", "beverage-mysql:3306", "-t", "30", "--",  "java", "-jar", "api.jar"]
#    environment:
#      DB_HOST: beverage-mysql
##    ports:
##      - "8080:8080"
#    networks:
#      - beverage-network
#    depends_on:
#      - beverage-mysql
#    deploy:
#      replicas: 2

  beverage-proxy:
    build: ./nginx
    image: beverage-proxy
    ports:
      - "80:80"
    networks:
      - beverage-network
    depends_on:
      - beverage-api